name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: xcodebuild test -scheme "Roundrect" -destination "platform=iOS Simulator,OS=14.4,name=iPhone 12"


